; ================================================================
;   SPRBank00.inc
;   Handles Sprite Bank 00
; 
;   Revision History:
;       Essam Erbab, April 2026: Created
; ================================================================

.segment "SPRBANK00"

    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00

    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $00, $00, $00, $00, $00, $00, $00, $00

    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

    .byte $06, $0F, $0D, $1F, $1E, $19, $6F, $BC
    .byte $0F, $09, $1E, $1B, $1B, $37, $FA, $CF

    .byte $FF, $6B, $3B, $1F, $1A, $1F, $1D, $3F
    .byte $BD, $FE, $3F, $3D, $1F, $1F, $1A, $3F

    ; .byte $FF, $77, $3F, $1F, $1A, $1F, $1F, $3F
    ; .byte $BD, $EE, $27, $3D, $1F, $1F, $1F, $3F

    ; .byte $00, $06, $0F, $0D, $1F, $1E, $19, $6F
    ; .byte $00, $0F, $09, $1E, $1B, $1B, $37, $FA

    ; .byte $BC, $FF, $6F, $25, $1A, $1F, $1B, $3F
    ; .byte $CF, $BD, $FE, $3F, $3F, $1F, $15, $3F

    ; .byte $06, $0F, $0D, $1F, $19, $1C, $69, $BE
    ; .byte $0F, $09, $1E, $1B, $1E, $37, $FF, $CD

    ; .byte $FF, $6F, $1B, $16, $1C, $1C, $1E, $3F
    ; .byte $BF, $FF, $3E, $1F, $1F, $1F, $1B, $3F

    ; .byte $FF, $77, $3F, $1E, $1C, $1C, $1E, $3F
    ; .byte $BF, $EF, $26, $3F, $1F, $1F, $1F, $3F

    ; .byte $00, $06, $0F, $0D, $1F, $19, $1C, $69
    ; .byte $00, $0F, $09, $1E, $1B, $1E, $37, $FF

    ; .byte $BE, $FF, $6F, $26, $1C, $1C, $1A, $3F
    ; .byte $CD, $BF, $FE, $3F, $3F, $1F, $17, $3F
    
    .byte $18, $24, $5A, $7E, $3C, $2C, $16, $0E
    .byte $3C, $7E, $66, $42, $66, $36, $3A, $1E


    .byte $00, $00, $00, $0F, $75, $BE, $AE, $B6
    .byte $00, $00, $00, $1F, $FB, $C1, $DF, $F9
    
    .byte $BE, $AE, $B6, $BC, $AE, $F9, $9E, $7F
    .byte $C1, $DF, $F9, $C3, $DF, $FF, $FF, $FF

    .byte $7F, $AE, $BC, $B6, $AE, $BE, $B6, $AE
    .byte $FF, $DF, $C3, $F9, $DF, $C1, $F9, $DF
  
    .byte $BE, $F5, $9E, $79, $0F, $00, $00, $00
    .byte $C1, $FB, $FF, $FF, $1F, $00, $00, $00

    .byte $3C, $5A, $B5, $FF, $DF, $BD, $5A, $3C 
    .byte $7E, $E7, $DB, $A1, $A1, $C3, $E7, $7E


    


    