; ================================================================
;   SPRBank00.inc
;   Handles Sprite Bank 00
; 
;   Revision History:
;       Essam Erbab, April 2026: Created
; ================================================================

.segment "SPRBANK00"

    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $00, $00, $00, $00, $00, $00, $00, $00

    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $00, $00, $00, $00, $00, $00, $00, $00

    .byte $00, $00, $00, $00, $00, $00, $00, $00
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF

    .byte $00, $00, $00, $0F, $75, $BE, $AE, $B6
    .byte $00, $00, $00, $1F, $FB, $C1, $DF, $F9
    
    .byte $BE, $AE, $B6, $BC, $AE, $F9, $9E, $7F
    .byte $C1, $DF, $F9, $C3, $DF, $FF, $FF, $FF

    .byte $7F, $AE, $BC, $B6, $AE, $BE, $B6, $AE
    .byte $FF, $DF, $C3, $F9, $DF, $C1, $F9, $DF
  
    .byte $BE, $F5, $9E, $79, $0F, $00, $00, $00
    .byte $C1, $FB, $FF, $FF, $1F, $00, $00, $00



    


    ; .byte $07, $0F, $0D, $07, $0C, $1F, $1B, $35
    ; .byte $07, $0E, $0A, $0F, $1F, $12, $3E, $2E

    ; .byte $3F, $6A, $7E, $3B, $0E, $0F, $0F, $1F
    ; .byte $77, $5F, $4D, $7F, $1F, $0D, $0F, $1F
    
    ; .byte $35, $3F, $5A, $4E, $3B, $0F, $09, $1F
    ; .byte $2E, $77, $7F, $7D, $7F, $1F, $0F, $1F

    ; .byte $3F, $2A, $1E, $0B, $0D, $0F, $0C, $1F
    ; .byte $37, $3F, $3D, $1F, $0F, $0B, $0F, $1F

    ; .byte $07, $0F, $0F, $07, $0C, $1F, $1B, $35
    ; .byte $07, $0F, $0F, $0F, $1B, $17, $3F, $2E

    ; .byte $07, $0F, $0F, $0E, $0B, $0E, $0B, $0D
    ; .byte $07, $0F, $0F, $0D, $07, $0F, $0C, $1E

    ; .byte $07, $0F, $0D, $07, $09, $0E, $0B, $0D
    ; .byte $07, $0F, $0A, $0F, $0F, $0B, $0E, $0E

    ; .byte $1F, $1A, $36, $3F, $1D, $0F, $0F, $1F
    ; .byte $17, $3F, $2D, $27, $3F, $1B, $0F, $1F

    ; .byte $0D, $1F, $0B, $0E, $0B, $0F, $0E, $1F
    ; .byte $1E, $17, $1F, $0F, $0E, $0F, $0F, $1F

    ; .byte $1F, $1A, $2E, $27, $1A, $0F, $09, $1F
    ; .byte $17, $3F, $3D, $3F, $3F, $1F, $0F, $1F